include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
