name: food_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  firebase_admin: ^0.3.0+2
  googleapis_auth: ^2.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  openfoodfacts: ^3.21.0
  postgres: ^3.5.6

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
