name: Deploy API to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4.2.2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.10
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'beta'

    - name: Build and push Docker image
      run: |
        docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT }}/food-api .
        docker push eu.gcr.io/${{ secrets.GCP_PROJECT }}/food-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy dart-frog-api \
          --image eu.gcr.io/${{ secrets.GCP_PROJECT }}/food-api \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
