name: Deploy API to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4.2.2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.10
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'beta'

    - name: Configure Docker Client of GCloud
      run: |-
        gcloud auth configure-docker
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/food-api/food-api .
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/food-api/food-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy food-api \
          --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/food-api/food-api \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=db.itlgaqflpmcwsnaivpgs.supabase.co" \
          --set-env-vars="DB_PORT=5432" \
          --set-env-vars="DB_NAME=postgres" \
          --set-env-vars="DB_USER=postgres" \
          --set-env-vars="DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
          --set-env-vars="DB_POOL_MAX_CONNECTIONS=10" \
          --set-env-vars="DB_POOL_MIN_CONNECTIONS=2" \
          --set-env-vars="DB_POOL_TIMEOUT=30" \
          --set-env-vars="DB_POOL_IDLE_TIMEOUT=10" \
          --set-env-vars="FIREBASE_PROJECT_ID=alimentos-21e88" \
          --set-env-vars="FIREBASE_PROJECT_NUMBER=217065923735" \
          --set-env-vars="FIREBASE_ANDROID_APP_ID=1:217065923735:android:840361874c4669f87ab5d2" \
          --set-env-vars="FIREBASE_WEB_APP_ID=1:217065923735:web:5135270693da2ec47ab5d2" \
          --set-env-vars="FIREBASE_SA_BASE64=${{ secrets.FIREBASE_SA_BASE64 }}"